name: Build Windows Wheel (cp313)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows-wheel:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up uv
        run: pip install uv

      - name: Build wheel with uv
        run: uv build

      - name: Upload wheel artifact
        uses: softprops/action-gh-release@v1
        with:
          name: windows-cp313-wheel
          files: dist/*.whl